name: Deploy 11ty & Upload to Cloudflare R2

on:
  push:
    branches:
      - main  # Change to your deployment branch
  workflow_dispatch: # Allow manual deployment
  
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Install AWS CLI
        run: |
          sudo apt update
          sudo apt install -y awscli

      - name: Build 11ty Site
        run: npm run build

      - name: Configure AWS CLI for Cloudflare R2
        run: |
          aws configure set aws_access_key_id ${{ secrets.R2_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.R2_SECRET_ACCESS_KEY }}
          aws configure set default.s3.endpoint_url ${{ secrets.R2_ENDPOINT }}
          aws configure set default.s3.signature_version s3v4

      - name: Upload Image Assets to Cloudflare R2
        run: |
          aws s3 sync _site/img s3://${{ secrets.R2_BUCKET }}/img \
          --endpoint-url=${{ secrets.R2_ENDPOINT }} \
          --acl public-read

      - name: Upload Video Assets to Cloudflare R2
        run: |
          aws s3 sync _site/video s3://${{ secrets.R2_BUCKET }}/video \
          --endpoint-url=${{ secrets.R2_ENDPOINT }} \
          --acl public-read

      - name: Purge Cloudflare Cache (Optional)
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE_ID }}/purge_cache" \
          -H "Authorization: Bearer ${{ secrets.CF_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          --data '{"purge_everything":true}'
